# Generated by Django 4.0.5 on 2022-09-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_purchase_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_model',
            name='comp',
        ),
    ]
