# Generated by Django 4.0.5 on 2022-09-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_purchase_model_itm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='purchase_model',
        ),
    ]
