# Generated by Django 4.0.5 on 2022-09-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_purchase_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('qnt', models.IntegerField()),
                ('brate', models.IntegerField()),
                ('bvalue', models.IntegerField()),
                ('addcost', models.IntegerField()),
                ('totalvalue', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('itm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item_crt')),
            ],
        ),
    ]
