# Generated by Django 4.0.5 on 2022-09-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_sale_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='analysis_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iquantity', models.IntegerField(null=True)),
                ('ieff_rate', models.IntegerField(null=True)),
                ('ivalue', models.IntegerField(null=True)),
                ('oquantity', models.IntegerField(null=True)),
                ('oeff_rate', models.IntegerField(null=True)),
                ('ovalue', models.IntegerField(null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item_crt')),
            ],
        ),
    ]
