# Generated by Django 4.0.5 on 2022-09-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_creategodown_under_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategodown',
            name='under_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock_item_crt'),
        ),
    ]
