# Generated by Django 4.0.5 on 2022-09-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_creategodown_under_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategodown',
            name='under_name',
            field=models.CharField(max_length=50),
        ),
    ]
