# Generated by Django 4.0.5 on 2022-09-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_creategodown_under_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateGodown',
        ),
    ]
