# Generated by Django 4.0.5 on 2022-09-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_countrymodel_statemodel_groupcreatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupanalysismodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perticular', models.CharField(max_length=250)),
                ('pquatity', models.IntegerField()),
                ('prate', models.IntegerField()),
                ('pvalue', models.IntegerField()),
                ('squatity', models.IntegerField()),
                ('srate', models.IntegerField()),
                ('svalue', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('pert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.groupcreatemodel')),
            ],
        ),
    ]
