# Generated by Django 4.0.5 on 2022-09-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_ledgercreatemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ledgercreatemodel',
        ),
    ]
