# Generated by Django 4.0.5 on 2022-09-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_ledgercreatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgeranalysismodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lperticular', models.CharField(max_length=250)),
                ('lpquatity', models.IntegerField()),
                ('lprate', models.IntegerField()),
                ('lpvalue', models.IntegerField()),
                ('lsquatity', models.IntegerField()),
                ('lsrate', models.IntegerField()),
                ('svalue', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('lpert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ledgercreatemodel')),
            ],
        ),
    ]
